project_id = "ejucuxeoxorythlrxapt"

[functions.wuzapi-proxy]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.public-payment]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false
